# LT 原稿（もりもり版） — Claude Code ハーネスエンジニアリングの変遷と運用 workflow

- 持ち時間: 8 分（スライドデザインは別途 ClaudeDesign に依頼）
- 聴衆: AI 開発実践者（同レベル）
- ゴール: 有用だった標準スキル / 効果が高かった自作スキル / ハーネス変遷（取り組み・壁・改善）の共有
- 想定枚数: 10 枚（現状もりもり = 約 9 分 30 秒、削り込みで 8 分に圧縮）

各スライドは以下の三部構成:

- **本文**: スライドに表示する文字（短く）
- **ねらい**: 話し手が話すときの方向性（箇条書き、アドリブ用）
- **画像案**: 差し込みビジュアルの内容

---

## [1] つかみ・自己紹介（30 秒）

### 本文

```
becky3 / 木部 暁（きべ さとる）

  20 年以上のソフトウェア開発実務
  直近 2 年はメタバース / ゲーム（UE5 / Blueprint）

  2026/2 〜、「準 LLM 無職」状態で Claude Code に没頭
  AI 開発領域へキャリアを拡げる学習中
```

### ねらい

- 「20 年以上の実務」で経験を裏付け、ベテラン色を提示
- 「メタバース / UE5」で直近領域を明示（AI 開発専業ではない出自）
- 「**準 LLM 無職**」を自己紹介ネタとして提示し、AI 開発実践者の聴衆と距離を縮める
- 「AI 開発領域へキャリアを拡げる」を本日のセッションの動機として接続
- 「LLM 無職」と「ニート」のニュアンス差は意識して使い分け（自発的選択・没頭の意味で）

### 画像案

- 名前 + アイコン（GitHub アバター等）を大きめに
- 直近 2 年（メタバース / UE5）と 2026/2〜現在（LLM）の時系列バー
- 「準 LLM 無職」をネタとしてキャッチコピー化

---

## [2] やったことざっくり — 規模感（30 秒）

### 本文

```
Claude Code で個人開発、3.5 ヶ月。

  899 PR
  2,951 commits
  133,697 行
  最大の 1 日: 94 commits

過去 1 年分の作業より、間違いなく多い。
```

### ねらい

- 数字 4 連発でインパクト
- 「個人開発」「3.5 ヶ月」を明示して、1 人での生産量という事実を強調
- 「過去 1 年分より多い」を**話し手の体感**として口頭で添える（正確な出典はないが、本人の実感としては確実）
- 「ハーネスを継続的に改善する」というテーマを冒頭で提示
- 「コードはほぼ全て Claude Code が書いた」を明示する

### 画像案

- 数字 4 つを大きく並べる（インフォグラフィック調）
- 「過去 1 年分より多い」を吹き出し or 補足キャプションで添える
- 「最大の 1 日: 94 commits」をハイライト

---

## [2] 取り組み概観 — 内訳と一般指標との対比（45 秒）

### 本文

```
5 リポ並行運用の内訳

| リポ           | PR  | commits |    LOC  |
|---------------|----:|--------:|--------:|
| agent-commons | 159 |     488 |  15,886 |
| rag-knowledge | 332 |   1,094 |  88,958 |
| ai-assistant  | 373 |   1,262 |  19,396 |
| article-writer|  23 |      71 |   5,998 |
| py-common-lib |  12 |      36 |   3,459 |
| **合計**      | **899** | **2,951** | **133,697** |

※ コードはほぼ Claude Code が書いた
```

### ねらい

- 内訳表で「ハーネス（agent-commons）と、それを使う側のリポ」の関係性を示す
- rag-knowledge の 88,958 行が突出して大きい点（実装ヘビーなリポ）
- Claude Code を使った場合の生産速度を数値で示す
- 「最大の 1 日: 94 commits」を再掲して規模感を強調
- 「Claude Code がほぼ全コードを書いた」を一言添える（誠実な前提開示）
- ここで言いたいのは **「Claude Code は速い」ではなく「速さに耐える運用が必要だった」** という伏線
- 残りの 8 分でその「運用」の話をする、と宣言

### 画像案

- 5 リポの内訳を横棒グラフ（PR / commits / LOC で 3 連）
- 中央に agent-commons（ハーネス）→ 4 リポ（利用側）の関係を示す簡易図
- 数字を 4 つ並べた数値カード（PR / commits / LOC / 1 日最大）

---

## [3] 有用だった Claude Code デフォルトスキル（30 秒）

### 本文

```
定着したデフォルトスキルは /loop

   /loop — 「定期実行を会話で組める」便利機構

一番効いたのは、Skill 機構そのもの
   SKILL.md を書くだけで、
   自分の運用ノウハウが「型」として残る

→ だから、自作スキルを 10 個以上作って育てた
```

### ねらい

- 事実をそのまま伝える：標準スキルで定着したのは `/loop` だけ
- `/loop` の用途：PR 監視・記事生成等のループ実行
- メッセージの核：**「デフォルトスキルそのもの」ではなく「Skill 機構（仕組み）」が一番効いた**
- SKILL.md を書く = 自分の運用ノウハウが型として残る、再利用可能になる
- このスライドは [4] への前振り（「だから自作スキルを大量に作った」）
- 30 秒なので、サクッと通過してすぐ次へ

### 画像案

- 左半分: デフォルトスキル一覧（薄く灰色）+ `/loop` だけハイライト
- 右半分: Skill 機構（SKILL.md 抽象アイコン）→ 自作スキル群（10 個アイコン）への矢印
- 「使ったのは 1 個、作ったのは 10+」の対比キャプション

---

## [4] 1 サイクルの workflow — 場面ごとのスキル使い分け（1 分 30 秒）

### 本文

```
Issue を 1 件片付けるサイクル（自作スキルの全体像）

 1. 復帰        /restore        前回ジャーナルから文脈復元
 2. 着手        /start-work     Issue 取得・worktree 作成
 3. 計画        /plan-work      影響範囲調査・完了基準合意
                                ※ Hook が計画なし編集を block
 4. 確認        /triage         複数項目は確認表ファイル方式
 5. レビュー    code-reviewer + doc-reviewer 並行実行
 6. 指摘対応    /triage         要修正は自動 / 要相談は確認表
 7. 締め        /auto-finalize  test → push → PR → 監視ループ
                                ※ gh pr create は Hook で経路ガード
 8. マージ後    /merged         チーム解散・ブランチ削除
 9. 引継ぎ      /handoff        ジャーナル化・課題 Issue 化
                                └→ 次サイクルの /restore に繋がる
```

### ねらい

- 9 ステップで 1 サイクルが完結する全体像を見せる
- スキルが「単発便利ツール」ではなく「1 つの運用システム」として結合
- `/handoff` で書いたジャーナルが次サイクルの `/restore` の入力になる **ループ構造**
- Hook の存在を 2 箇所で軽く言及（[7] で深掘り予告）
- 聴衆が「自分でもこの workflow を組みたい」と思える具体度を意識
- 1 分 30 秒は短くないので、流れを早めに見せて余白を「なぜこうなったか」に使う

### 画像案

- 9 ステップを円環状に配置（1 → 2 → … → 9 → 1 のループ）
- 各ステップにスキル名と短い説明
- 9（handoff）→ 1（restore）を太い矢印でループ強調
- Hook 介入箇所（ステップ 3 後の編集 / ステップ 7 内の gh pr create）を赤い縦線でハイライト
- Hook 介入箇所（/plan-work 後の編集 / /auto-finalize 後の gh pr create）を赤い縦線でハイライト

---

## [5] ハーネス変遷 ① — 共通化フェーズ（1 分）

### 本文

```
最初の壁: ルールとスキルが、リポごとにバラバラに増殖

→ agent-commons という SSoT リポを作った
→ dotfiles 経由で ~/.claude/ に展開
→ 仕様書も改革: 42 ファイル → 30 ファイル

学び: 「読め」より「注入する」
   CLAUDE.md に「README 読め」と書いても読まれない
   → SessionStart Hook で自動注入
```

### ねらい

- 最初に直面した課題: 各リポで似たような Claude Code 設定を書き散らしていた
- agent-commons リポを作り SSoT 化、dotfiles で `~/.claude/` に展開
- 仕様書改革 (#572) で 42→30 ファイル、5 日間 22 セッション
- パイロット 6 ファイルで 1980 行 → 729 行（**約 63% 削減**）
- 一番の教訓: 「**読め、より、注入する**」
  - 指示書に「読め」と書いても AI は読まないことがある
  - SessionStart Hook で「読ませるべき内容」を自動注入
  - これは [7] の Hook 議論の伏線

### 画像案

- Before/After 比較図
  - Before: 各リポに散らばる設定ファイル群（カオスな図）
  - After: agent-commons 中心の整理された構造
- 数字: 42→30 ファイル、1980→729 行（63% 削減）
- 「読め → 注入する」のキャッチフレーズを大きく

---

## [6] ハーネス変遷 ② — チーム機構の壁（1 分）

### 本文

```
やってみた: AI エージェントチームで品質レビュー

DEATH NOTE チーム（5 人）で議論
→ 100M コンテキスト時代に再設計
→ fixed-theme / mixed-genius を統合
→ ストーリーテラー廃止（リューク発言できなかった）
→ 511 行削減

学び: パターンの存在意義は時代で変わる
   100M 時代に「コスト削減型」は不要に
```

### ねらい

- 「AI エージェントを複数人立てて議論させる」という発想
- 初期は fixed-theme（同一テーマ専門家）/ mixed-genius（多様な視点）の 2 パターン併用
- 100M コンテキスト時代に再設計（Issue #150, PR #151）
- パターン統合の決め手: **メンバー全員が独立に同じ結論に到達**
- ストーリーテラー廃止の理由が面白い: 役割を持たせたら発言できなくなった構造的問題
- 「100M 時代になって、コスト削減型のパターンの存在意義が薄れた」という時代依存の判断
- 学び: AI 機構の設計は固定ではなく、モデルの進化に合わせて更新する

### 画像案

- 左: DEATH NOTE チーム 5 人のアイコン（キャラ名は架空のプレースホルダーに）
- 右: 2 パターン統合の Before/After
- 511 行削減を数字でハイライト

---

## [7] ハーネス変遷 ③ — scope drift と /plan-work + Hook（1 分 30 秒）

### 本文

```
中盤の大きな壁: AI が「ついで」で勝手に直す
→ scope drift（指示外への暴走）

最初の対策: ルール文書で「やらないで」と書く
→ 効かない（advisory 遵守率 27%）

次の対策: /plan-work スキル + PreToolUse Hook
   1. Issue 着手時に /plan-work で計画ファイル作成
   2. 計画ファイルがない状態での編集を Hook が deny
   3. 計画外の修正は計画ファイル更新で記録

結果: v0.1 → v0.2 で 50 → 79 点（評価者 2 名平均）

学び: AI の自律性を制御するなら、ルールではなく仕組み
```

### ねらい

- 中盤で一番悩んだ問題: AI が指示範囲外を自動で変更する
- 例: 「typo 直して」と頼んだら、ついでに別ファイルもリファクタした
- ルール文書（advisory）で「やらないで」と書いても**遵守率 27%**
- 解決策の構造:
  - `/plan-work` で計画ファイルを `aidlc-docs/plan-work/issue-N.md` に作る
  - PreToolUse Hook で「計画ファイル不在時の Edit/Write を deny」
  - 計画外の修正が必要になったら、まず計画ファイルを更新する習慣
- 結果は定量で出ている: 評価 50→79 点
- ここで [5] の「読め、より、注入する」の伏線回収
- 学び: 「**AI の自律性を制御するなら、ルール（advisory）ではなく仕組み（hard gate）**」

### 画像案

- ビフォーアフター: 「ルール文書だけ」vs「ルール + Hook」の効果差
- Hook ブロック画面のスクリーンショット風イラスト（Edit が deny される瞬間）
- 50→79 点の棒グラフ

---

## [8] ハーネス変遷 ④ — 確認フロー疲れ → /triage 統一（45 秒）

### 本文

```
後半の壁: 確認の聞き方が散らかる
   AskUserQuestion を連発 → user が前後比較できない
   どこまで確認するかの基準がブレる

→ /triage スキルで統一
   - 1 項目: AskUserQuestion
   - 2 項目以上: 確認表ファイル方式

成果（ドッグフード結果）:
   要確認 81.25% → 0/15 件
```

### ねらい

- ある程度自作スキルが溜まってきたら、今度は「**ユーザーへの確認の仕方**」が散らかった
- AskUserQuestion を連発する AI / 何でも勝手に進める AI / 確認の粒度がバラバラ
- `/triage` スキルで確認ルールを一本化
  - 1 項目なら AskUserQuestion（即応性重視）
  - 2 項目以上は確認表ファイル方式（俯瞰しながら記入）
- ドッグフーディング結果:
  - **ベースライン: 要確認 81.25%**
  - **新フロー後: 0/15 件**
- 学び: 過剰な確認を構造で抑える

### 画像案

- 確認表ファイル方式の画面イラスト（チェックボックスが並ぶ）
- 81.25% → 0/15 件 の改善グラフ

---

## [9] その他提案（30 秒）

### 本文

```
おまけ: 派生的に効いた仕組み

A) Slack 経由リモート操作
   スマホから Claude Code セッションを起動
   REMOTE_SLACK_SESSION=1 で UI 動線を切り替え

B) ジャーナル → RAG パイプライン
   /handoff で書いたジャーナルを自動で RAG に投入
   翌セッションの /restore で意味検索可能に
```

### ねらい

- 派生して効いた仕組みを 2 つ紹介（軽め）
- A: Slack 経由のリモート操作。外出先からスマホで Claude Code を起動
  - `code` コマンドが使えない問題を環境変数で動線切り替え
- B: ジャーナル → RAG（rag-knowledge）への自動取り込み
  - 698 件のジャーナルが意味検索可能
  - 「過去にこの問題どう解決したっけ」を rag_search で引ける
- どちらも「ハーネス（共通設定）と他リポの組み合わせ」で実現できた

### 画像案

- A: スマホ → Slack → Claude Code セッションの動線図
- B: handoff → ジャーナル → RAG → restore のループ図

---

## [予備] これから検証したいこと（時間余ったら、30〜60 秒）

8 分の主構成からは外す。終盤で時間が余った場合のみ提示する予備スライド。

### 本文

```
ハーネスは今、コードの外に出ようとしている

   unityMCP             — AI が Unity を直接操作
   BlenderMCP           — AI が 3D アセットを直接編集
   Chrome DevTools MCP  — AI がブラウザを直接動かす

→ 「ルール vs 仕組み」の議論が、コードを超えて広がっていく
```

### ねらい

- LT 主軸の「ハーネス成長記」を**未来の展望**で締める予備枠
- 3 つの MCP に共通する方向性: **AI が外部ツールを「直接」操作する世界**
- 従来: 人間がツール操作 → AI が支援
- これから: AI がツール直接操作 → 人間がレビュー
- ハーネスの守備範囲が「コード書き」から「3D アセット・UI 操作」に拡大していく
- F16（Plugin Marketplace）と連続する話題として、後半セクションの自然な延長

### 画像案

- 3 つの MCP アイコンを並べ、それぞれの操作対象（Unity / Blender / Chrome）を図示
- 「コードを超えて広がる」を示す矢印

---

## [10] まとめ（30 秒）

### 本文

```
持ち帰ってほしいこと

1. Skill 機構は「自分の運用を型にする」道具
2. AI の自律性を制御するならルールではなく仕組み（Hook）
3. ハーネスは自分で使って、自分で直す
```

### ねらい

- 3 つに圧縮して提示
- 1: スキル機構の本質的価値
- 2: scope drift の話の核心（核メッセージ）
- 3: 自分で使って自分で直す運用スタンス
- 質問・連絡先案内の余白を 5-10 秒残す
- ※ user 構成案では [6]「終わりに」に置き換え予定（LLM の失敗と寛容な心のメッセージ）

### 画像案

- 3 つの持ち帰りポイントを大きく並べる
- 下部に SNS / GitHub ハンドル

---

## 削り込みのための「優先度メモ」

8 分に圧縮する際、以下の優先順で削る候補:

### 削りやすい（削っても LT が成立する）

- [9] その他提案 → 30 秒丸ごとカット可能（残す場合は A か B どちらかに）
- [6] チーム機構の壁 → 「やってみたが時代で変わった」だけ言って 30 秒短縮可能
- [3] デフォルトスキル → 「`/init` と Skill 機構」だけ言って 30 秒短縮可能

### 削りにくい（核心）

- [5] 共通化フェーズ — 「読め、より、注入する」が [7] の伏線
- [7] scope drift と Hook — 定量効果あり、核心メッセージ
- [8] /triage — 定量効果あり、聴衆が刺さる数字
- [4] workflow ストーリー — 真似しやすさの肝

### 候補プラン: 8 分版

- [9] カット（30 秒削減）
- [6] を 30 秒に圧縮（30 秒削減）
- → 計 1 分削減で 8 分 30 秒 → さらに各章の話し方で 30 秒圧縮可能

---

## 確認したい点

このもりもり版に対するフィードバック観点:

1. **構成全体**: 章の順序・各章の主張は LT のゴールに合致しているか
2. **温度感**: 「読め、より、注入する」等のキーワードは刺さるか
3. **数字の使い方**: 50→79 点 / 81.25%→0/15 件 / 27% 遵守率 / 63% 削減 は印象的に出ているか
4. **削り込み**: 削るべきは [9] か [6] か、それとも別の章か
5. **画像案**: 不足してる箇所はあるか、もっと印象的にできるか

ご意見ください。
